services:
  product-db:
    image: postgres:16-alpine
    restart: always
    container_name: product-db-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: products
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
